name: genshin_renderer
description: Renders hoYoLab JSON API information

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  web_renderer: ^0.0.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - resources/images/genshin/
  fonts:
    - family: GenshinImpact
      fonts:
        - asset: resources/fonts/genshin.ttf
    - family: DIN
      fonts:
        - asset: resources/fonts/DIN.ttf
