name: genshin_renderer
description: Renders hoYoLab JSON API information

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  web_renderer: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - resources/images/genshin/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: resources/fonts/RobotoMono-Bold.ttf
          weight: 400
        - asset: resources/fonts/RobotoMono-BoldItalic.ttf
          weight: 400
        - asset: resources/fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: resources/fonts/RobotoMono-ExtraLightItalic.ttf
          weight: 200
        - asset: resources/fonts/RobotoMono-Italic.ttf
          weight: 400
        - asset: resources/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: resources/fonts/RobotoMono-LightItalic.ttf
          weight: 300
        - asset: resources/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: resources/fonts/RobotoMono-MediumItalic.ttf
          weight: 500
        - asset: resources/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: resources/fonts/RobotoMono-SemiBold.ttf
          weight: 400
        - asset: resources/fonts/RobotoMono-SemiBoldItalic.ttf
          weight: 400
        - asset: resources/fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: resources/fonts/RobotoMono-ThinItalic.ttf
          weight: 100
