name: Client Build

on:
  workflow_call:
  push:
    branches:
      - master

jobs:
  compile:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v2

      - name: Flutter Install
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: |
             flutter pub get
             sudo apt update
             sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
             flutter config --enable-linux-desktop

      - name: Build Executable
        run: flutter build linux --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/linux/x64/release/bundle

      # - name: Build failed
      #   if: failure()
      #   run: python3 .github/workflows/deployer.py build_failed

      #- name: Build succeeded
      #   if: success()
      #   run: python3 .github/workflows/deployer.py build_succeeded
